export const GET_DETAIL_REQUEST = "GET_DETAIL_REQUEST"
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS"
export const GET_DETAIL_FAILURE = "GET_DETAIL_FAILURE"

export const GET_DETAIL_SUCCESS_GENRE = "GET_DETAIL_SUCCESS_GENRE"
export const GET_DETAIL_SUCCESS_PLATFORMS = "GET_DETAIL_SUCCESS_PLATFORMS"
export const GET_DETAIL_SUCCESS_DEVELOPERS = "GET_DETAIL_SUCCESS_DEVELOPERS"
export const GET_DETAIL_SUCCESS_PUBLISHER = "GET_DETAIL_SUCCESS_PUBLISHER"